# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('crawlers', 'crawlers'),
        ('data_processing', 'data_processing'),
        ('utils', 'utils'),
        ('test_crawler.py', '.'),
        ('main.py', '.'),
    ],
    hiddenimports=[
        'bs4',
        'requests',
        'pandas',
        'fake_useragent',
        'pdfplumber',
        'lxml',
        'selenium',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'threading',
        'datetime',
        'json',
        'csv',
        're',
        'logging',
        'os',
        'sys',
        'time',
        'random',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'soupsieve',
        'numpy',
        'python_dateutil',
        'pytz',
        'tzdata',
        'pdfminer',
        'PIL',
        'cryptography',
        'cffi',
        'pycparser',
        'six',
        'trio',
        'trio_websocket',
        'websocket_client',
        'attrs',
        'sortedcontainers',
        'outcome',
        'sniffio',
        'wsproto',
        'h11',
        'pysocks',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='高考数据采集系统',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为False以隐藏控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 可以添加图标文件路径
) 